import { Activity, AudioLines, BookOpenCheck, CheckCircle2, ClipboardList, FilePenLine, LayoutDashboard, LockKeyhole, LogOut, Plus, ShieldCheck, Sparkles, UsersRound, XCircle } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import "./admin.css";

type AdminTab = "overview" | "story" | "lore" | "audio" | "validation";

const tabs: { id: AdminTab; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "story", label: "Story editor", icon: FilePenLine },
  { id: "lore", label: "Codex & album", icon: BookOpenCheck },
  { id: "audio", label: "Audio catalog", icon: AudioLines },
  { id: "validation", label: "Publish validation", icon: ClipboardList },
];

export default function Admin() {
  const [, setLocation] = useLocation();
  const session = trpc.admin.session.useQuery();
  const logout = trpc.admin.logout.useMutation({ onSuccess: () => session.refetch() });
  const [activeTab, setActiveTab] = useState<AdminTab>("overview");

  if (session.isLoading) return <div className="admin-loading">Opening the archive…</div>;
  if (!session.data?.authenticated) return <OwnerLogin onAuthenticated={() => session.refetch()} onLeave={() => setLocation("/")} />;

  return <main className="admin-shell">
    <aside className="admin-sidebar"><div className="admin-brand"><span>S</span><div><b>Shadows</b><em>Owner console</em></div></div><p className="eyebrow">Private editorial workspace</p><nav>{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} className={activeTab === tab.id ? "is-active" : ""} onClick={() => setActiveTab(tab.id)}><Icon size={16} /> {tab.label}</button>; })}</nav><div className="admin-sidebar__footer"><button onClick={() => setLocation("/")}><Sparkles size={15} /> Public experience</button><button onClick={() => logout.mutate()}><LogOut size={15} /> Lock console</button></div></aside>
    <section className="admin-main"><header className="admin-topbar"><div><p className="eyebrow">Restricted archive</p><h1>{tabs.find(tab => tab.id === activeTab)?.label}</h1></div><div className="admin-status"><ShieldCheck size={16} /><span>Owner session active</span></div></header>{activeTab === "overview" && <Overview />}{activeTab === "story" && <StructuredStoryEditor />}{activeTab === "lore" && <LoreEditor />}{activeTab === "audio" && <AudioEditor />}{activeTab === "validation" && <ValidationPanel />}</section>
  </main>;
}

function OwnerLogin({ onAuthenticated, onLeave }: { onAuthenticated: () => void; onLeave: () => void }) {
  const [identifier, setIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const login = trpc.admin.login.useMutation({ onSuccess: onAuthenticated });
  const submit = (event: FormEvent) => { event.preventDefault(); login.mutate({ identifier, password }); };
  return <main className="owner-login"><form onSubmit={submit}><div className="owner-login__mark"><LockKeyhole size={25} /></div><p className="eyebrow">Restricted archive</p><h1>Owner console</h1><p>Enter the private credentials issued at handoff. Player progress and story saves are never visible here.</p><label>Owner identifier<input autoComplete="username" value={identifier} onChange={event => setIdentifier(event.target.value)} placeholder="SOTC-XXXXXXXX" /></label><label>Passphrase<input type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} placeholder="••••••••••••" /></label>{login.error && <div className="form-error">{login.error.message}</div>}<button className="button-primary" disabled={login.isPending}>{login.isPending ? "Verifying…" : "Unlock console"}</button><button type="button" className="button-secondary" onClick={onLeave}>Return to game</button></form></main>;
}

function Overview() {
  const dashboard = trpc.admin.dashboard.useQuery();
  const data = dashboard.data;
  if (dashboard.isLoading) return <div className="admin-skeleton">Reading the city’s signals…</div>;
  return <div className="admin-view"><section className="metric-grid"><Metric icon={UsersRound} label="Anonymous installations" value={data?.installations ?? 0} /><Metric icon={Activity} label="Game starts" value={data?.starts ?? 0} /><Metric icon={CheckCircle2} label="Completed cases" value={data?.completions ?? 0} /><Metric icon={ClipboardList} label="Recorded events" value={data?.events ?? 0} /></section><section className="admin-grid-two"><article className="admin-card"><div className="card-heading"><h2>Chapter reach</h2><span>Unique installations</span></div><div className="bar-chart">{data?.chapterReach.map(point => <div key={point.chapter}><span>CH {String(point.chapter).padStart(2, "0")}</span><i><b style={{ width: `${Math.min(100, (point.reached / Math.max(1, data.installations)) * 100)}%` }} /></i><em>{point.reached}</em></div>)}</div></article><article className="admin-card"><div className="card-heading"><h2>Choice signals</h2><span>Most selected</span></div>{data?.choices.length ? <ol className="choice-metrics">{data.choices.map(choice => <li key={choice.id}><span>{choice.id.replace(/^CH\d+_S\d+_N\d+-/, "")}</span><b>{choice.count}</b></li>)}</ol> : <EmptyCopy text="Choices will appear here after anonymous players begin tracing the case." />}</article></section><section className="privacy-note"><ShieldCheck size={17} /><p><strong>Privacy boundary:</strong> these counts are anonymous aggregates. No save file, character choice text, account identity or personal information is available to the console.</p></section></div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: number }) { return <article className="metric-card"><Icon size={18} /><div><b>{value.toLocaleString()}</b><span>{label}</span></div></article>; }

function ContentEditor({ kind }: { kind: "story-node" | "codex" | "character" }) {
  const content = trpc.admin.content.useQuery();
  const utils = trpc.useUtils();
  const save = trpc.admin.saveContent.useMutation({ onSuccess: () => utils.admin.content.invalidate() });
  const [editingId, setEditingId] = useState(""); const [title, setTitle] = useState(""); const [chapter, setChapter] = useState("1"); const [payload, setPayload] = useState('{\n  "nextId": "",\n  "imageUrl": ""\n}');
  const items = content.data?.filter(item => item.kind === kind) ?? [];
  const submit = (event: FormEvent) => { event.preventDefault(); try { save.mutate({ id: editingId || undefined, kind, title, chapter: Number(chapter), status: "published", payload: JSON.parse(payload) }); setTitle(""); } catch { /* JSON feedback is rendered below */ } };
  const edit = (item: NonNullable<typeof content.data>[number]) => { setEditingId(item.id); setTitle(item.title); setChapter(String(item.chapter ?? 1)); setPayload(JSON.stringify(item.payload, null, 2)); };
  return <div className="admin-view"><section className="admin-grid-two content-grid"><article className="admin-card"><div className="card-heading"><h2>Existing {kind === "story-node" ? "story nodes" : "files"}</h2><span>{items.length} saved</span></div>{items.length ? <div className="content-list">{items.map(item => <button className="content-list__item" onClick={() => edit(item)} key={item.id}><span><b>{item.title}</b><small>{item.status} · {item.chapter ? `Chapter ${item.chapter}` : "Global"}</small></span><code>{item.id}</code></button>)}</div> : <EmptyCopy text="The initial runtime uses the approved script data. Save an editorial override here to begin managed revisions." />}</article><article className="admin-card"><div className="card-heading"><h2>{editingId ? "Edit published item" : "New editorial item"}</h2><span>{editingId || "Draft"}</span></div><form className="admin-form" onSubmit={submit}><label>Title<input required value={title} onChange={event => setTitle(event.target.value)} placeholder="e.g. CH1_S1_N01" /></label><label>Chapter<select value={chapter} onChange={event => setChapter(event.target.value)}>{Array.from({ length: 10 }, (_, index) => <option key={index + 1}>{index + 1}</option>)}</select></label><label>Structured payload<textarea value={payload} onChange={event => setPayload(event.target.value)} rows={8} /></label>{save.error && <div className="form-error">{save.error.message}</div>}<button className="button-primary" disabled={save.isPending}><Plus size={15} /> {save.isPending ? "Saving…" : editingId ? "Publish update" : "Save published item"}</button></form></article></section></div>;
}

type ChoiceForm = { id: string; label: string; target: string };

function StructuredStoryEditor() {
  const content = trpc.admin.content.useQuery(); const utils = trpc.useUtils();
  const save = trpc.admin.saveContent.useMutation({ onSuccess: () => utils.admin.content.invalidate() });
  const items = content.data?.filter(item => item.kind === "story-node") ?? [];
  const [selectedId, setSelectedId] = useState(""); const [title, setTitle] = useState(""); const [chapter, setChapter] = useState("1"); const [imageUrl, setImageUrl] = useState(""); const [nextId, setNextId] = useState(""); const [narration, setNarration] = useState(""); const [speaker, setSpeaker] = useState(""); const [dialogue, setDialogue] = useState(""); const [choices, setChoices] = useState<ChoiceForm[]>([{ id: "A", label: "", target: "" }]);
  const load = (item: NonNullable<typeof content.data>[number]) => { const payload = item.payload as Record<string, unknown>; const blocks = Array.isArray(payload.blocks) ? payload.blocks as { type?: string; text?: string; speaker?: string }[] : []; const firstDialogue = blocks.find(block => block.type === "dialogue"); setSelectedId(item.id); setTitle(item.title); setChapter(String(item.chapter ?? 1)); setImageUrl(typeof payload.imageUrl === "string" ? payload.imageUrl : ""); setNextId(typeof payload.nextId === "string" ? payload.nextId : ""); setNarration(blocks.filter(block => block.type === "narration").map(block => block.text ?? "").join("\n\n")); setSpeaker(firstDialogue?.speaker ?? ""); setDialogue(firstDialogue?.text ?? ""); setChoices(Array.isArray(payload.choices) && payload.choices.length ? payload.choices as ChoiceForm[] : [{ id: "A", label: "", target: "" }]); };
  const updateChoice = (index: number, field: keyof ChoiceForm, value: string) => setChoices(choices.map((choice, candidate) => candidate === index ? { ...choice, [field]: value } : choice));
  const submit = (event: FormEvent) => { event.preventDefault(); const blocks = [...(narration.trim() ? narration.split(/\n{2,}/).map(text => ({ type: "narration", text })) : []), ...(dialogue.trim() ? [{ type: "dialogue", speaker: speaker || "NICK", text: dialogue }] : [])]; save.mutate({ id: selectedId || undefined, kind: "story-node", title, chapter: Number(chapter), status: "published", payload: { imageUrl, nextId, blocks, choices: choices.filter(choice => choice.label.trim() && choice.target.trim()) } }); };
  return <div className="admin-view"><section className="admin-grid-two content-grid"><article className="admin-card"><div className="card-heading"><h2>Story nodes</h2><span>{items.length} published</span></div><div className="content-list compact">{items.map(item => <button className="content-list__item" onClick={() => load(item)} key={item.id}><span><b>{item.title}</b><small>Chapter {item.chapter} · {item.status}</small></span><code>{item.id}</code></button>)}</div></article><article className="admin-card"><div className="card-heading"><h2>{selectedId ? "Edit node" : "New node"}</h2><span>{selectedId || "Draft"}</span></div><form className="admin-form structured-form" onSubmit={submit}><label>Node title<input required value={title} onChange={event => setTitle(event.target.value)} placeholder="CH1_S1_N01" /></label><label>Chapter<select value={chapter} onChange={event => setChapter(event.target.value)}>{Array.from({ length: 10 }, (_, index) => <option key={index + 1}>{index + 1}</option>)}</select></label><label>Scene image URL<input required value={imageUrl} onChange={event => setImageUrl(event.target.value)} placeholder="/manus-storage/…" /></label><label>Continue destination<input value={nextId} onChange={event => setNextId(event.target.value)} placeholder="CH1_S1_N02" /></label><label>Narration<textarea value={narration} onChange={event => setNarration(event.target.value)} rows={5} /></label><div className="inline-pair"><label>Dialogue speaker<input value={speaker} onChange={event => setSpeaker(event.target.value)} placeholder="NICK" /></label><label>Dialogue line<input value={dialogue} onChange={event => setDialogue(event.target.value)} placeholder="A line of dialogue" /></label></div><div className="form-subheading"><span>Choices</span><button type="button" onClick={() => setChoices([...choices, { id: String.fromCharCode(65 + choices.length), label: "", target: "" }])}>+ Add choice</button></div>{choices.map((choice, index) => <div className="choice-fields" key={`${choice.id}-${index}`}><input aria-label="Choice label" value={choice.label} onChange={event => updateChoice(index, "label", event.target.value)} placeholder="Choice copy" /><input aria-label="Choice target" value={choice.target} onChange={event => updateChoice(index, "target", event.target.value)} placeholder="Destination node" /></div>)}<button className="button-primary" disabled={save.isPending}><FilePenLine size={15} /> {save.isPending ? "Publishing…" : "Publish node"}</button></form></article></section></div>;
}

function StructuredLoreEditor({ kind }: { kind: "codex" | "character" }) {
  const content = trpc.admin.content.useQuery(); const utils = trpc.useUtils(); const save = trpc.admin.saveContent.useMutation({ onSuccess: () => utils.admin.content.invalidate() });
  const items = content.data?.filter(item => item.kind === kind) ?? []; const [selectedId, setSelectedId] = useState(""); const [title, setTitle] = useState(""); const [chapter, setChapter] = useState("1"); const [summary, setSummary] = useState(""); const [imageUrl, setImageUrl] = useState("");
  const load = (item: NonNullable<typeof content.data>[number]) => { const payload = item.payload as Record<string, unknown>; setSelectedId(item.id); setTitle(item.title); setChapter(String(item.chapter ?? 1)); setSummary(typeof payload.summary === "string" ? payload.summary : ""); setImageUrl(typeof payload.imageUrl === "string" ? payload.imageUrl : ""); };
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate({ id: selectedId || undefined, kind, title, chapter: Number(chapter), status: "published", payload: { summary, imageUrl, unlockChapter: Number(chapter) } }); };
  return <section className="admin-grid-two content-grid"><article className="admin-card"><div className="card-heading"><h2>{kind === "codex" ? "Codex entries" : "Album cards"}</h2><span>{items.length} published</span></div><div className="content-list compact">{items.map(item => <button className="content-list__item" onClick={() => load(item)} key={item.id}><span><b>{item.title}</b><small>Unlocks Chapter {item.chapter}</small></span><code>{item.id}</code></button>)}</div></article><article className="admin-card"><div className="card-heading"><h2>{selectedId ? "Edit entry" : "New entry"}</h2><span>{selectedId || "Draft"}</span></div><form className="admin-form structured-form" onSubmit={submit}><label>Title<input required value={title} onChange={event => setTitle(event.target.value)} /></label><label>Unlock chapter<select value={chapter} onChange={event => setChapter(event.target.value)}>{Array.from({ length: 10 }, (_, index) => <option key={index + 1}>{index + 1}</option>)}</select></label><label>Summary<textarea value={summary} onChange={event => setSummary(event.target.value)} rows={4} /></label>{kind === "character" && <label>Character sheet URL<input value={imageUrl} onChange={event => setImageUrl(event.target.value)} placeholder="/manus-storage/…" /></label>}<button className="button-primary"><BookOpenCheck size={15} /> Publish entry</button></form></article></section>;
}

function LoreEditor() { const [mode, setMode] = useState<"codex" | "character">("codex"); return <div className="admin-view"><div className="segmented"><button className={mode === "codex" ? "is-active" : ""} onClick={() => setMode("codex")}>Codex entries</button><button className={mode === "character" ? "is-active" : ""} onClick={() => setMode("character")}>Album cards</button></div><StructuredLoreEditor kind={mode} /></div>; }

function AudioEditor() {
  const assets = trpc.admin.audioAssets.useQuery(); const assignments = trpc.admin.audioAssignments.useQuery(); const utils = trpc.useUtils();
  const save = trpc.admin.saveAudioAsset.useMutation({ onSuccess: () => utils.admin.audioAssets.invalidate() }); const upload = trpc.admin.uploadAudio.useMutation({ onSuccess: () => utils.admin.audioAssets.invalidate() }); const assign = trpc.admin.assignAudio.useMutation({ onSuccess: () => utils.admin.audioAssignments.invalidate() });
  const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [category, setCategory] = useState<"music" | "ambience" | "sfx">("ambience"); const [selected, setSelected] = useState(""); const [targetType, setTargetType] = useState<"chapter" | "scene" | "node">("chapter"); const [targetId, setTargetId] = useState("1");
  const handleUpload = async (file: File) => { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; bytes.forEach(byte => { binary += String.fromCharCode(byte); }); upload.mutate({ fileName: file.name, mimeType: file.type || "audio/mpeg", base64: btoa(binary) }); };
  return <div className="admin-view"><section className="admin-grid-two content-grid"><article className="admin-card"><div className="card-heading"><h2>Audio assets</h2><span>{assets.data?.length ?? 0} cataloged</span></div><form className="admin-form" onSubmit={event => { event.preventDefault(); save.mutate({ name, url, category }); }}><label>Asset name<input required value={name} onChange={event => setName(event.target.value)} placeholder="Harbor fog loop" /></label><label>Category<select value={category} onChange={event => setCategory(event.target.value as typeof category)}><option value="music">Music</option><option value="ambience">Ambience</option><option value="sfx">SFX</option></select></label><label>Public audio URL<input required type="url" value={url} onChange={event => setUrl(event.target.value)} placeholder="https://…" /></label><button className="button-primary"><Plus size={15} /> Catalog asset</button></form><label className="audio-upload">Or upload an audio file<input type="file" accept="audio/*" onChange={event => { const file = event.target.files?.[0]; if (file) handleUpload(file); }} />{upload.isPending && <small>Uploading securely…</small>}</label><div className="content-list compact">{assets.data?.map(asset => <div key={asset.id}><span><b>{asset.name}</b><small>{asset.category}</small></span><code>{asset.id}</code></div>)}</div></article><article className="admin-card"><div className="card-heading"><h2>Assign audio</h2><span>Non-blocking cue</span></div><form className="admin-form" onSubmit={event => { event.preventDefault(); if (selected) assign.mutate({ audioAssetId: selected, targetType, targetId }); }}><label>Audio asset<select value={selected} onChange={event => setSelected(event.target.value)}><option value="">Select an asset</option>{assets.data?.map(asset => <option value={asset.id} key={asset.id}>{asset.name}</option>)}</select></label><label>Attach to<select value={targetType} onChange={event => setTargetType(event.target.value as typeof targetType)}><option value="chapter">Chapter</option><option value="scene">Scene</option><option value="node">Story node</option></select></label><label>Target ID<input value={targetId} onChange={event => setTargetId(event.target.value)} placeholder="1 or CH1_S1_N01" /></label><button className="button-primary" disabled={!selected}><AudioLines size={15} /> Assign cue</button></form><div className="content-list compact">{assignments.data?.map(item => <div key={item.id}><span><b>{item.targetType}: {item.targetId}</b><small>Volume {item.volume}% · {item.loop ? "loop" : "one shot"}</small></span><code>{item.audioAssetId}</code></div>)}</div></article></section></div>;
}

function ValidationPanel() { const result = trpc.admin.validate.useQuery(); const lists = useMemo(() => result.data ? [{ label: "Broken destinations", values: result.data.brokenDestinations }, { label: "Missing images", values: result.data.missingImages }, { label: "Unreachable nodes", values: result.data.unreachable }] : [], [result.data]); return <div className="admin-view"><section className="validation-hero"><CheckCircle2 size={23} /><div><p className="eyebrow">Pre-publish checks</p><h2>Keep the case coherent</h2><p>Validation inspects owner-managed story overrides before they are published. The approved runtime remains available until a replacement is valid.</p></div></section><section className="validation-grid">{lists.map(list => <article className="admin-card" key={list.label}><div className="card-heading"><h2>{list.label}</h2>{list.values.length ? <XCircle color="#df8b77" size={18} /> : <CheckCircle2 color="#c9a66a" size={18} />}</div>{list.values.length ? <ul>{list.values.map(value => <li key={value}>{value}</li>)}</ul> : <EmptyCopy text="No issues detected." />}</article>)}</section><p className="validation-total">Managed story nodes currently indexed: <b>{result.data?.totalNodes ?? 0}</b></p></div>; }

function EmptyCopy({ text }: { text: string }) { return <p className="empty-copy">{text}</p>; }
