import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { readSettings, writeSettings } from "@/lib/gameState";

export type Locale = "en" | "fa";

const copy: Record<Locale, Record<string, string>> = {
  en: { codex: "Codex", album: "Album", settings: "Settings", archive: "Archive", newGame: "New game", continue: "Continue", returnToArchive: "Back to the archive", yourMove: "Your move", loading: "Loading the case…", brandTitle: "Shadows", brandSubtitle: "of the city", chapterShort: "CH.", caseFile: "Case file / 001", interactiveNoir: "An interactive noir novel", homeDek: "The city forgets what it needs to survive. You were never meant to remember.", codexLink: "The codex", albumLink: "Character album", playerSettings: "Player settings", localSave: "Your progress stays in this browser.", replaceCase: "Replace current case", beginInvestigation: "Begin a new investigation?", replaceWarning: "Your current progress, choices and unlocked files on this browser will be replaced.", beginAgain: "Begin again", keepSave: "Keep my save", fieldNotes: "Field notes", codexTitle: "The Codex", codexDek: "Everything the city has allowed you to understand — and everything it has kept closed.", allFiles: "All files", characters: "Characters", places: "Places", organizations: "Organizations", symbols: "Symbols", evidence: "Evidence", searchFiles: "Search unlocked files", classified: "Classified", fileLocked: "This file is sealed until Chapter {chapter}.", knownFaces: "Known faces", albumTitle: "Character Album", albumDek: "Portraits become clearer as the story makes room for them.", unlocksChapter: "Unlocks in Chapter {chapter}", unknown: "Unknown", expressionSheet: "{name} expression sheet", setAtmosphere: "Set the atmosphere", reading: "Reading", textSize: "Text size", highContrast: "High contrast", highContrastHint: "Sharpen panels and text against scenes.", reducedMotion: "Reduced motion", reducedMotionHint: "Removes non-essential transitions.", sceneEffects: "Scene effects", sceneEffectsHint: "Fog, grain, and light leaks.", sound: "Sound", muteAudio: "Mute all audio", muteHint: "Audio remains optional at every moment.", music: "Music", ambience: "Ambience", effects: "Sound effects", language: "Language", active: "Active", persianStatus: "Persian Chapter 1 available · RTL ready", privacy: "Privacy", anonymousInsights: "Anonymous gameplay insights", telemetryHint: "Sends only non-identifying progress and choice events. Your save never leaves this browser.", resetSave: "Reset local save", resetPrompt: "Erase local progress, choices and unlocks from this browser?", eraseProgress: "Erase progress", keepIt: "Keep it", scene: "Scene {scene}", traced: "{percent}% traced", closeCase: "Close the case", openCodex: "Open codex", openAlbum: "Open character album", openSettings: "Open settings", controls: "Toggle controls", untranslatedChapter: "The Persian edition currently includes Chapter 1. This chapter is shown in English while translation continues." },
  fa: { codex: "کدکس", album: "آلبوم", settings: "تنظیمات", archive: "بایگانی", newGame: "بازی جدید", continue: "ادامه", returnToArchive: "بازگشت به بایگانی", yourMove: "انتخاب شما", loading: "در حال بارگذاری پرونده…", brandTitle: "سایه‌های شهر", brandSubtitle: "", chapterShort: "فصل", caseFile: "پرونده / ۰۰۱", interactiveNoir: "رمان نوآر تعاملی", homeDek: "شهر آن‌چه را برای بقا لازم دارد فراموش می‌کند. تو هرگز قرار نبود به یاد بیاوری.", codexLink: "کدکس", albumLink: "آلبوم شخصیت‌ها", playerSettings: "تنظیمات بازیکن", localSave: "پیشرفت شما در همین مرورگر می‌ماند.", replaceCase: "جایگزینی پرونده فعلی", beginInvestigation: "تحقیق تازه‌ای آغاز شود؟", replaceWarning: "پیشرفت، انتخاب‌ها و پرونده‌های بازشده فعلی در این مرورگر جایگزین می‌شوند.", beginAgain: "شروع دوباره", keepSave: "حفظ ذخیره", fieldNotes: "یادداشت‌های میدانی", codexTitle: "کدکس", codexDek: "هرآنچه شهر اجازه داده بفهمی — و هرآنچه پنهان نگه داشته است.", allFiles: "همه پرونده‌ها", characters: "شخصیت‌ها", places: "مکان‌ها", organizations: "سازمان‌ها", symbols: "نمادها", evidence: "شواهد", searchFiles: "جست‌وجوی پرونده‌های بازشده", classified: "طبقه‌بندی‌شده", fileLocked: "این پرونده تا فصل {chapter} مهروموم است.", knownFaces: "چهره‌های شناخته‌شده", albumTitle: "آلبوم شخصیت‌ها", albumDek: "پرتره‌ها با پیشروی داستان روشن‌تر می‌شوند.", unlocksChapter: "بازشدن در فصل {chapter}", unknown: "ناشناخته", expressionSheet: "شیت حالت‌های {name}", setAtmosphere: "تنظیم حال‌وهوا", reading: "خواندن", textSize: "اندازه متن", highContrast: "کنتراست بالا", highContrastHint: "پنل‌ها و متن را روی صحنه‌ها واضح‌تر می‌کند.", reducedMotion: "حرکت کاهش‌یافته", reducedMotionHint: "حرکت‌های غیرضروری را حذف می‌کند.", sceneEffects: "افکت‌های صحنه", sceneEffectsHint: "مه، دانه‌بندی و نورهای گذرا.", sound: "صدا", muteAudio: "بی‌صدا کردن همه صداها", muteHint: "صدا در همه لحظه‌ها اختیاری است.", music: "موسیقی", ambience: "اتمسفر", effects: "افکت‌های صوتی", language: "زبان", active: "فعال", persianStatus: "نسخه فارسی کامل و راست‌به‌چپ آماده است", privacy: "حریم خصوصی", anonymousInsights: "بینش ناشناس از بازی", telemetryHint: "تنها رخدادهای ناشناس پیشرفت و انتخاب ارسال می‌شود. ذخیره شما هرگز از مرورگر خارج نمی‌شود.", resetSave: "بازنشانی ذخیره محلی", resetPrompt: "پیشرفت، انتخاب‌ها و موارد بازشده همین مرورگر پاک شوند؟", eraseProgress: "پاک‌کردن پیشرفت", keepIt: "حفظ", scene: "صحنه {scene}", traced: "{percent}٪ پیگیری‌شده", closeCase: "بستن پرونده", openCodex: "بازکردن کدکس", openAlbum: "بازکردن آلبوم شخصیت‌ها", openSettings: "بازکردن تنظیمات", controls: "نمایش کنترل‌ها", untranslatedChapter: "ترجمه فارسی این بخش در دسترس نیست و متن انگلیسی نمایش داده می‌شود." },
};

type LocaleContextValue = { locale: Locale; direction: "ltr" | "rtl"; setLocale: (locale: Locale) => void; t: (key: string, variables?: Record<string, string | number>) => string; persianAvailable: boolean };
const LocaleContext = createContext<LocaleContextValue | null>(null);

export function LocaleProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => {
    if (typeof window !== "undefined") {
      const requestedLocale = new URLSearchParams(window.location.search).get("lang");
      if (requestedLocale === "en" || requestedLocale === "fa") return requestedLocale;
    }
    return readSettings().locale;
  });
  const direction: "ltr" | "rtl" = locale === "fa" ? "rtl" : "ltr";
  useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = direction; }, [locale, direction]);
  const setLocale = (nextLocale: Locale) => { setLocaleState(nextLocale); writeSettings({ ...readSettings(), locale: nextLocale }); };
  const value = useMemo(() => ({ locale, direction, setLocale, t: (key: string, variables: Record<string, string | number> = {}) => Object.entries(variables).reduce((message, [name, value]) => message.replace(`{${name}}`, String(value)), copy[locale][key] ?? copy.en[key] ?? key), persianAvailable: true }), [locale, direction]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale() {
  const value = useContext(LocaleContext);
  if (!value) throw new Error("useLocale must be used inside LocaleProvider");
  return value;
}
