-- Shadows of the City: private server-backed data model for Supabase/PostgreSQL.
-- The Express/tRPC server uses a server-only key. Browser roles receive no table grants.

create or replace function public.sotc_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_signed_in timestamptz not null default timezone('utc', now())
);

create table if not exists public.editorial_content (
  id text primary key,
  kind text not null check (kind in ('story-node', 'codex', 'character', 'configuration')),
  title text not null,
  chapter integer check (chapter between 1 and 10),
  status text not null default 'draft' check (status in ('draft', 'published')),
  payload jsonb not null,
  updated_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audio_assets (
  id text primary key,
  name text not null,
  category text not null check (category in ('music', 'ambience', 'sfx')),
  url text not null,
  duration_seconds integer check (duration_seconds >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audio_assignments (
  id text primary key,
  audio_asset_id text not null references public.audio_assets(id) on delete cascade,
  target_type text not null check (target_type in ('chapter', 'scene', 'node')),
  target_id text not null,
  volume integer not null default 70 check (volume between 0 and 100),
  loop boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.telemetry_events (
  id text primary key,
  installation_id text not null,
  event_type text not null check (event_type in ('game_start', 'node_view', 'choice_selected', 'chapter_reached', 'game_complete')),
  chapter integer check (chapter between 1 and 10),
  node_id text,
  choice_id text,
  locale text not null default 'en',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.owner_credentials (
  id bigint generated by default as identity primary key,
  identifier text not null unique,
  password_salt text not null,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.localized_story_overrides (
  id text primary key,
  locale text not null default 'fa' check (locale = 'fa'),
  scene_title text not null,
  blocks jsonb not null,
  choice_labels jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.admin_sessions (
  id text primary key,
  credential_id bigint not null references public.owner_credentials(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists telemetry_events_type_created_at_idx on public.telemetry_events (event_type, created_at desc);
create index if not exists telemetry_events_installation_id_idx on public.telemetry_events (installation_id);
create index if not exists telemetry_events_chapter_idx on public.telemetry_events (chapter);
create index if not exists admin_sessions_expires_at_idx on public.admin_sessions (expires_at);
create index if not exists audio_assignments_target_idx on public.audio_assignments (target_type, target_id);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.sotc_set_updated_at();
drop trigger if exists editorial_content_set_updated_at on public.editorial_content;
create trigger editorial_content_set_updated_at before update on public.editorial_content for each row execute function public.sotc_set_updated_at();
drop trigger if exists audio_assets_set_updated_at on public.audio_assets;
create trigger audio_assets_set_updated_at before update on public.audio_assets for each row execute function public.sotc_set_updated_at();
drop trigger if exists audio_assignments_set_updated_at on public.audio_assignments;
create trigger audio_assignments_set_updated_at before update on public.audio_assignments for each row execute function public.sotc_set_updated_at();
drop trigger if exists owner_credentials_set_updated_at on public.owner_credentials;
create trigger owner_credentials_set_updated_at before update on public.owner_credentials for each row execute function public.sotc_set_updated_at();
drop trigger if exists localized_story_overrides_set_updated_at on public.localized_story_overrides;
create trigger localized_story_overrides_set_updated_at before update on public.localized_story_overrides for each row execute function public.sotc_set_updated_at();

alter table public.users enable row level security;
alter table public.editorial_content enable row level security;
alter table public.audio_assets enable row level security;
alter table public.audio_assignments enable row level security;
alter table public.telemetry_events enable row level security;
alter table public.owner_credentials enable row level security;
alter table public.localized_story_overrides enable row level security;
alter table public.admin_sessions enable row level security;

revoke all on table public.users, public.editorial_content, public.audio_assets, public.audio_assignments, public.telemetry_events, public.owner_credentials, public.localized_story_overrides, public.admin_sessions from anon, authenticated;
grant select, insert, update, delete on table public.users, public.editorial_content, public.audio_assets, public.audio_assignments, public.telemetry_events, public.owner_credentials, public.localized_story_overrides, public.admin_sessions to service_role;
grant usage, select on all sequences in schema public to service_role;
